### ISSUE TITLE
是否暴露了自己的 CloudFlare API key了？

### ISSUE THREAD

**Issue by ggggarlic** [imroc/kubernetes-practice-guide#1]
https://github.com/imroc/kubernetes-practice-guide/blob/master/best-practice/cert-management/autogenerate-certificate-with-cert-manager.md#%E5%88%9B%E5%BB%BA%E9%A2%81%E5%8F%91%E6%9C%BA%E6%9E%84-clusterissuerissuer

**Comment by ggggarlic** [comment]
secret

**Comment by imroc** [comment]
并没有，是故意改错过的apikey，无效的，也感谢善意提醒。
